# docs: https://www.chezmoi.io/reference/special-files-and-directories/chezmoiexternal-format/
# examples: https://www.chezmoi.io/user-guide/include-files-from-elsewhere/

".irssi/themes":
    type: "git-repo"
    url: "git@github.com:irssi-import/themes.git"
    refreshPeriod: "168h"

".vim/autoload/pathogen.vim":
    type: "file"
    url: "https://github.com/tpope/vim-pathogen/raw/master/autoload/pathogen.vim"
    refreshPeriod: "168h"

".vim/bundle/catppuccin-vim":
    type: "git-repo"
    url: "git@github.com:catppuccin/vim.git"
    refreshPeriod: "168h"

".vim/bundle/ctrlp":
    type: "git-repo"
    url: "git@github.com:ctrlpvim/ctrlp.vim.git"
    refreshPeriod: "168h"

".vim/bundle/fzf":
    type: "git-repo"
    url: "git@github.com:junegunn/fzf.git"
    refreshPeriod: "168h"

".vim/bundle/nerdtree":
    type: "git-repo"
    url: "git@github.com:preservim/nerdtree.git"
    refreshPeriod: "168h"

".vim/bundle/rainbow_csv":
    type: "git-repo"
    url: "git@github.com:mechatroner/rainbow_csv.git"
    refreshPeriod: "168h"

".vim/bundle/vim-fugitive":
    type: "git-repo"
    url: "git@github.com:tpope/vim-fugitive.git"
    refreshPeriod: "168h"

".vim/bundle/vim-ledger":
    type: "git-repo"
    url: "git@github.com:ledger/vim-ledger.git"
    refreshPeriod: "168h"

".vim/bundle/vim-startify":
    type: "git-repo"
    url: "git@github.com:mhinz/vim-startify.git"
    refreshPeriod: "168h"

".vim/bundle/vim-table-mode":
    type: "git-repo"
    url: "git@github.com:dhruvasagar/vim-table-mode.git"
    refreshPeriod: "168h"

".vim/bundle/vimwiki":
    type: "git-repo"
    url: "git@github.com:vimwiki/vimwiki.git"
    refreshPeriod: "168h"

