# docs: https://www.chezmoi.io/reference/special-files-and-directories/chezmoiexternal-format/
# examples: https://www.chezmoi.io/user-guide/include-files-from-elsewhere/

".vim/autoload/pathogen.vim":
    type: "file"
    url: "https://github.com/tpope/vim-pathogen/raw/master/autoload/pathogen.vim"
    refreshPeriod: "168h"
